const PRODUCTS = [
  {
    "id": 1,
    "name": "Thịt bò xẻ miếng",
    "price": 100000,
    "image": "img/product/product-1.jpg",
    "discount": 0,
    "color": "white",
    "size": "small",
    "stock": 100,
    "weight": 1,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "111Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 2,
    "name": "Chuối",
    "price": 35000,
    "image": "img/product/product-2.jpg",
    "discount": 0,
    "color": "white",
    "size": "small",
    "stock": 0,
    "weight": 1,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "2222Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 3,
    "name": "Ổi ruột đỏ",
    "price": 20000,
    "image": "img/product/product-3.jpg",
    "discount": 0,
    "color": "blue",
    "size": "small",
    "stock": 100,
    "weight": 1,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "3333Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 4,
    "name": "Nho đen Mỹ",
    "price": 110000,
    "image": "img/product/product-4.jpg",
    "discount": 0,
    "color": "black",
    "size": "tiny",
    "stock": 100,
    "weight": 13,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 5,
    "name": "Hamburger",
    "price": 20000,
    "image": "img/product/product-5.jpg",
    "discount": 0,
    "color": "green",
    "size": "tiny",
    "stock": 100,
    "weight": 4,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 6,
    "name": "Xoài Thái",
    "price": 25000,
    "image": "img/product/product-6.jpg",
    "discount": 0,
    "color": "green",
    "size": "small",
    "stock": 100,
    "weight": 1,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 7,
    "name": "Dưa hấu",
    "price": 10000,
    "image": "img/product/product-7.jpg",
    "discount": 0,
    "color": "white",
    "size": "tiny",
    "stock": 100,
    "weight": 5,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 8,
    "name": "Táo Nauy",
    "price": 90000,
    "image": "img/product/product-8.jpg",
    "discount": 0,
    "color": "yellow",
    "size": "tiny",
    "stock": 100,
    "weight": 4,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 9,
    "name": "Mận đen",
    "price": 45000,
    "image": "img/product/product-9.jpg",
    "discount": 0,
    "color": "red",
    "size": "large",
    "stock": 100,
    "weight": 4,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 10,
    "name": "Gà rán",
    "price": 35000,
    "image": "img/product/product-10.jpg",
    "discount": 0,
    "color": "red",
    "size": "medium",
    "stock": 100,
    "weight": 1,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 11,
    "name": "Nước cam",
    "price": 12000,
    "image": "img/product/product-11.jpg",
    "discount": 0,
    "color": "red",
    "size": "tiny",
    "stock": 100,
    "weight": 5,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 12,
    "name": "Hoa quả tổng hợp",
    "price": 80000,
    "image": "img/product/product-12.jpg",
    "discount": 0,
    "color": "red",
    "size": "small",
    "stock": 100,
    "weight": 7,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 13,
    "name": "Thị bò xẻ miếng 222",
    "price": 10000,
    "image": "img/product/product-1.jpg",
    "discount": 0,
    "color": "green",
    "size": "small",
    "stock": 100,
    "weight": 4,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 14,
    "name": "Chuối 222",
    "price": 8000,
    "image": "img/product/product-2.jpg",
    "discount": 0,
    "color": "black",
    "size": "medium",
    "stock": 100,
    "weight": 10,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 15,
    "name": "Ổi ruột đỏ 222",
    "price": 11000,
    "image": "img/product/product-3.jpg",
    "discount": 0,
    "color": "green",
    "size": "large",
    "stock": 100,
    "weight": 1,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 16,
    "name": "Nho đen Mỹ 222",
    "price": 11000,
    "image": "img/product/product-4.jpg",
    "discount": 0,
    "color": "black",
    "size": "large",
    "stock": 100,
    "weight": 17,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 17,
    "name": "Hamburger 222",
    "price": 11000,
    "image": "img/product/product-5.jpg",
    "discount": 0,
    "color": "green",
    "size": "medium",
    "stock": 100,
    "weight": 9,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 18,
    "name": "Xoài Thái 222",
    "price": 11000,
    "image": "img/product/product-6.jpg",
    "discount": 0,
    "color": "blue",
    "size": "tiny",
    "stock": 100,
    "weight": 7,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 19,
    "name": "Dưa hấu 222",
    "price": 11000,
    "image": "img/product/product-7.jpg",
    "discount": 0,
    "color": "green",
    "size": "medium",
    "stock": 100,
    "weight": 7,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 20,
    "name": "Táo Nauy 222",
    "price": 90000,
    "image": "img/product/product-8.jpg",
    "discount": 0,
    "color": "blue",
    "size": "small",
    "stock": 100,
    "weight": 5,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 21,
    "name": "Mận đen 222",
    "price": 11000,
    "image": "img/product/product-9.jpg",
    "discount": 0,
    "color": "blue",
    "size": "medium",
    "stock": 100,
    "weight": 13,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 22,
    "name": "Gà rán 222",
    "price": 100000,
    "image": "img/product/product-10.jpg",
    "discount": 0,
    "color": "white",
    "size": "small",
    "stock": 100,
    "weight": 4,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 23,
    "name": "Nước cam 222",
    "price": 11000,
    "image": "img/product/product-11.jpg",
    "discount": 0,
    "color": "red",
    "size": "medium",
    "stock": 100,
    "weight": 13,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 24,
    "name": "Hoa quả tổng hợp 222",
    "price": 13000,
    "image": "img/product/product-12.jpg",
    "discount": 0,
    "color": "green",
    "size": "tiny",
    "stock": 100,
    "weight": 3,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 25,
    "name": "Hoa quả tổng hợp 3333",
    "price": 115000,
    "image": "img/product/product-12.jpg",
    "discount": 0,
    "color": "blue",
    "size": "large",
    "stock": 100,
    "weight": 17,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 26,
    "name": "Hoa quả sấy khô",
    "price": 50000,
    "image": "img/product/discount/pd-1.jpg",
    "discount": 10,
    "color": "yellow",
    "size": "tiny",
    "stock": 100,
    "weight": 1,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 27,
    "name": "Rau củ tổng hợp",
    "price": 85000,
    "image": "img/product/discount/pd-2.jpg",
    "discount": 10,
    "color": "black",
    "size": "small",
    "stock": 100,
    "weight": 9,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 28,
    "name": "Sữa chua uống vị cam",
    "price": 15000,
    "image": "img/product/discount/pd-3.jpg",
    "discount": 20,
    "color": "yellow",
    "size": "medium",
    "stock": 100,
    "weight": 17,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 29,
    "name": "Xoài xoài",
    "price": 85000,
    "image": "img/product/discount/pd-4.jpg",
    "discount": 20,
    "color": "red",
    "size": "medium",
    "stock": 100,
    "weight": 1,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 30,
    "name": "Mcdonald's burger",
    "price": 35000,
    "image": "img/product/discount/pd-5.jpg",
    "discount": 15,
    "color": "white",
    "size": "small",
    "stock": 100,
    "weight": 17,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  },
  {
    "id": 31,
    "name": "Nho China",
    "price": 45000,
    "image": "img/product/discount/pd-6.jpg",
    "discount": 100,
    "color": "yellow",
    "size": "tiny",
    "stock": 100,
    "weight": 3,
    "collections": [
      "https://picsum.photos/400",
      "https://picsum.photos/400?a",
      "https://picsum.photos/400?b",
      "https://picsum.photos/400?c"
    ],
    "introduction": "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
    "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eius quibusdam, voluptatum a similique tempore ratione id maiores corporis doloribus consequuntur, voluptates libero voluptas quasi animi explicabo assumenda cupiditate! Voluptate?",
    "information": "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Proin eget tortor risus.",
    "review": "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a."
  }
]